name: SwiftDating
options:
  bundleIdPrefix: com.gregdeveloper1
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  SwiftDating:
    type: application
    platform: iOS
    sources:
      - path: NativeDating
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gregdeveloper1.SwiftDating
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "SwiftDating needs camera access to take profile photos"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "SwiftDating needs photo library access to select profile photos"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "SwiftDating uses your location to find people nearby"
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Supabase
    entitlements:
      path: NativeDating/SwiftDating.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
